### ISSUE TITLE
orderby attribute error

### ISSUE THREAD

**Issue by massimiliano-cannata** [istSOS/istSOS4#4]
**Request:**
/istsos4/v1.1/Things%283%29/Datastreams?%24expand=Observations%28%24select%3DphenomenonTime%2Cresult%3B%24orderby%3DphenomenonTime+asc%3B%24top%3D34050%29

**Error:**
File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 2501, in visit_textual_label_reference
api-1         |     coercions._no_text_coercion(
api-1         |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 585, in _no_text_coercion
api-1         |     raise exc_cls(
api-1         | sqlalchemy.exc.CompileError: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'phenomenon_time' should be explicitly declared as text('phenomenon_time')
api-1         | INFO:     172.18.0.5:45304 - "GET /istsos4/v1.1/Things%283%29/Datastreams?%24expand=Observations%28%24select%3DphenomenonTime%2Cresult%3B%24orderby%3DphenomenonTime+asc%3B%24top%3D34050%29 HTTP/1.1" 400 Bad Request

**Comment by ClaudioPrimerano** [comment]
Fixed orderby in the expand node

[commit details](https://github.com/istSOS/istSOS4/commit/096645809acd3574a41db264a074a447e23932a3)
