### ISSUE TITLE
Missing required property 'Geometry has Z dimension but column does no'

### ISSUE THREAD

**Issue by danistrigaro** [istSOS/istSOS4#5]
Error when I insert a Location with the Z (x,y,z)

Error message:
{"code":400,"type":"error","message":"Missing required property 'Geometry has Z dimension but column does no'"}

**Comment by ClaudioPrimerano** [comment]
An **EPSG** environment variable has been introduced, which defines the coordinate system for all geometry fields.
Additionally, the system now supports the inclusion of geometry with a Z dimension (3D coordinates).

[commit details](https://github.com/istSOS/istSOS4/commit/d1d9e42e2bf1e2fd55b5736e31fa6381a65d5292)
