### ISSUE TITLE
The system supports only EPSG:4326

### ISSUE THREAD

**Issue by danistrigaro** [istSOS/istSOS4#6]
When I try to insert a Location with a geometry in the Swiss National EPSG:2056 an error occurs saying that only epsg:4326 is supported.

**Comment by ClaudioPrimerano** [comment]
An **EPSG** environment variable has been introduced, which defines the coordinate system for all geometry fields.
Additionally, the system now supports the inclusion of geometry with a Z dimension (3D coordinates).

[commit details](https://github.com/istSOS/istSOS4/commit/d1d9e42e2bf1e2fd55b5736e31fa6381a65d5292)
