### ISSUE TITLE
Add an option to disable "Duplicates"

### ISSUE THREAD

**Issue by danistrigaro** [istSOS/istSOS4#7]
In sensorThings Api software implementations such as FROST, there is no control on the entity's name duplication.

e.g. you can add/POST the same Thing as many times as you like with a returning status code of 201.

It would be nice to have an env variable to let the user choose to stay with this behavior or disable it to raise an error when an entity is inserted with the same name of another one. This feature will help to remove/prevent redundant values in the database.

**Comment by ClaudioPrimerano** [comment]
The environment variable **DUPLICATES** has been added, which, if set to false, does not allow the insertion of already existing values.
This check is managed at the database level through the addition of constraints.
A **UNIQUE** constraint is applied to the *name* column for all entities and to the *phenomenonTime* and *datastream_id* columns for the Observation.

[commit details](https://github.com/istSOS/istSOS4/commit/f426302dbde0415fbed3a61d1e9291fbdcddd61e)
