### ISSUE TITLE
Add a env parameter to set unqiue values for a datastream

### ISSUE THREAD

**Issue by danistrigaro** [istSOS/istSOS4#8]
To avoid duplicated values on a datastream, it should be very nice to have an env parameter to enable the addition of a unique constraint between result, phenomenonTime and datastream_fk_id in the observations table .
So, when a client tries to insert the same Observation the software can block it and responding to the client with an error message that says that this observation is still existing.

**Comment by ClaudioPrimerano** [comment]
The environment variable **DUPLICATES** has been added, which, if set to false, does not allow the insertion of already existing values.
This check is managed at the database level through the addition of constraints.
A **UNIQUE** constraint is applied to the *name* column for all entities and to the *phenomenonTime* and *datastream_id* columns for the Observation.

[commit details](https://github.com/istSOS/istSOS4/commit/f426302dbde0415fbed3a61d1e9291fbdcddd61e)
