### ISSUE TITLE
$orderby=phenomenonTime desc is not working in the expand

### ISSUE THREAD

**Issue by danistrigaro** [istSOS/istSOS4#9]
This request:
http://xena.dacd.supsi.ch:8018/boschetti/v1.1/Datastreams?$filter=name%20eq%20%27HA_FIU_VAL%27&$expand=Observations($orderby=resultTime%20desc)

return:
{"code":400,"type":"error","message":"Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'result_time' should be explicitly declared as text('result_time')"}

**Comment by ClaudioPrimerano** [comment]
Fixed orderby in the expand node

[commit details](https://github.com/istSOS/istSOS4/commit/096645809acd3574a41db264a074a447e23932a3)
